# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bd7959218a40ce4039a84bb7bc0d2fc8e2929a9aee8a1faded586f4a25debcd0db699ee8b880e120944aaa7486beefc7a26b70af2c5727919c7b7720bed6ac0

test:
  secret_key_base: 3d694b96464dd2b60b7a89be2a849481f5db8b970bffb744e6cccd071876e6062fdc0582c14d0b39a723889669332ba3b13a169bebaa87685e2df435ca19505a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
